# Generated by Django 4.1.3 on 2022-12-07 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_endereco_ong_pet_usuario_vacina_delete_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='ong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.ong'),
        ),
    ]
