# Generated by Django 2.2.19 on 2022-12-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_auto_20221130_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AddField(
            model_name='pet',
            name='codPet',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
