# Generated by Django 4.1.3 on 2022-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_auto_20221205_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('Escolha uma opção', 'Escolha uma opção')], default='Escolha uma opção', max_length=17),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tipo',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outro', 'Outro'), ('Escolha uma opção', 'Escolha uma opção')], default='Escolha uma opção', max_length=17),
        ),
    ]
