# Generated by Django 2.2.19 on 2022-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_auto_20221201_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pelo',
            field=models.CharField(choices=[('C', 'Curto'), ('L', 'Longo'), ('S P', 'Sem Pelo')], default='Escolha uma opção', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='Escolha uma opção', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
