# Generated by Django 2.2.19 on 2022-12-01 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_ong_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='codPet',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
